### ISSUE TITLE
Is there a plan to update monix-nio to Monix 3.0.0-RC2

### ISSUE THREAD

**Issue by kartavtcev** [monix/monix-nio#23]
Hello,

just tried to run monix-nio 0.0.3 with Monix 3.0.0-RC2
got error in the lib, because of Callback was moved to monix.execution
Just wondering, shall we expect a version update here?

(Okay, I see now, it works on Monix 3.0.0-RC1)

Thank you!

**Comment by kartavtcev** [comment]
Okay, I see now, it works on Monix 3.0.0-RC1

**Comment by scubamaggo** [comment]
I ran into the same problem and did a little bit of work to make it compile and pass tests with the new monix version. I could take care of this issue.

**Comment by radusw** [comment]
**v0.0.4** has been released and it depends on **Monix 3.0.0-RC2**. Thank you for your cotribution @scubamaggo
